"use client";

import { useMemo, useState } from "react";
import { Badge, CapabilityRow, Empty, Modal, card, field, primary, secondary } from "./components";
import { CAPABILITIES, PERSONAS, effective, labelFor, personaAllows, personaChoice, personaCounts, todayInColombo, type Capability, type DemoState, type Member, type Persona } from "./model";

type Actions = { onDetails: (capability: Capability, member?: Member, persona?: Persona) => void; onEdit: (capability?: Capability, member?: Member, persona?: Persona) => void };

export function PeopleScreen({ state, selected, setSelected, filterPersona, setFilterPersona, actions, viewer, onAddMember }: { state: DemoState; selected: string | null; setSelected: (id: string | null) => void; filterPersona: Persona | "all"; setFilterPersona: (value: Persona | "all") => void; actions: Actions; viewer: "admin" | "super_admin"; onAddMember: () => void }) {
  const [query, setQuery] = useState("");
  const [exceptionsOnly, setExceptionsOnly] = useState(false);
  const [memberTab, setMemberTab] = useState<"access" | "profile" | "scope">("access");
  const [showUnavailable, setShowUnavailable] = useState(false);
  const member = state.members.find((item) => item.id === selected && !item.personas.includes("super_admin"));
  const visible = state.members.filter((item) => !item.personas.includes("super_admin") && (filterPersona === "all" || item.personas.includes(filterPersona)) && (!exceptionsOnly || state.exceptions.some((ex) => ex.memberId === item.id)) && `${item.name} ${item.email}`.toLowerCase().includes(query.toLowerCase()));

  if (member) {
    const protectedMember = member.personas.some((persona) => persona === "admin" || persona === "super_admin");
    const relevant = CAPABILITIES.filter((item) => member.personas.some((persona) => item.relevant.includes(persona)) || state.exceptions.some((ex) => ex.memberId === member.id && ex.action === item.action));
    const allowed = relevant.filter((item) => effective(state, member, item).allowed);
    const exceptions = state.exceptions.filter((ex) => ex.memberId === member.id);
    return <div className="space-y-5">
      <button className="min-h-11 text-sm font-semibold text-[#0a6b63]" onClick={() => setSelected(null)}>← Back to people</button>
      <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-[#58685f]">People / {member.name}</p><h2 className="mt-1 text-3xl font-semibold">{member.name}</h2><p className="text-[#58685f]">{member.personas.map(labelFor).join(" + ")} · {member.email}</p></div><Badge tone={member.active ? "green" : "neutral"}>{member.active ? "Active member" : "Inactive"}</Badge></div>
      <div className="flex flex-wrap gap-2 border-b border-[#d9e3de]">{(["access", "profile", "scope"] as const).map((tab) => <button key={tab} className={`min-h-11 border-b-2 px-4 text-sm font-semibold capitalize ${memberTab === tab ? "border-[#0a6b63] text-[#0a6b63]" : "border-transparent text-[#58685f]"}`} onClick={() => setMemberTab(tab)}>{tab}</button>)}</div>
      {memberTab === "profile" && <div className={`${card} p-6`}><h3 className="text-lg font-semibold">Profile</h3><dl className="mt-4 grid gap-4 sm:grid-cols-2"><div><dt className="text-sm text-[#58685f]">Staff ID</dt><dd>{member.id}</dd></div><div><dt className="text-sm text-[#58685f]">Email</dt><dd>{member.email}</dd></div><div><dt className="text-sm text-[#58685f]">Persona</dt><dd>{member.personas.map(labelFor).join(" + ")}</dd></div>{member.vehicleType && <div><dt className="text-sm text-[#58685f]">Vehicle type</dt><dd className="capitalize">{member.vehicleType}</dd></div>}</dl></div>}
      {memberTab === "scope" && <div className={`${card} p-6`}><h3 className="text-lg font-semibold">Assigned places</h3><p className="mt-1 text-sm text-[#58685f]">Capabilities work only within these existing assignments. This demo does not change assignments.</p><div className="mt-4 flex flex-wrap gap-2">{member.places.length ? member.places.map((place) => <Badge key={place} tone="blue">{place === "GLOBAL" ? "All depots" : place}</Badge>) : <Badge tone="amber">No place assigned</Badge>}{member.vehicleType && <Badge tone="blue">{member.vehicleType === "van" ? "Van" : "Truck"}</Badge>}</div></div>}
      {memberTab === "access" && <>
        <div className="grid gap-4 sm:grid-cols-3"><Summary value={allowed.length} label="Effective capabilities"/><Summary value={exceptions.length} label="Member exceptions"/><Summary value={member.places.length} label="Assigned places"/></div>
        <section className={`${card} p-5 sm:p-6`}><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-lg font-semibold">Member exceptions</h3><p className="text-sm text-[#58685f]">These choices apply only to {member.name.split(" ")[0]}.</p></div><button className={primary} disabled={protectedMember && viewer !== "super_admin" || member.personas.includes("super_admin")} onClick={() => actions.onEdit(undefined, member)}>+ Add exception</button></div>
          {exceptions.length === 0 ? <p className="mt-5 text-sm text-[#58685f]">No exceptions. This member uses persona access.</p> : <div className="mt-4 divide-y divide-[#e9efea]">{exceptions.map((ex) => { const capability = CAPABILITIES.find((item) => item.action === ex.action); const expired = !!ex.expires && ex.expires < todayInColombo(); return <div key={ex.action} className="flex flex-wrap items-center gap-3 py-3"><div className="flex-1"><p className="font-semibold">{capability?.label ?? ex.action}</p><p className="text-sm text-[#58685f]">{ex.place ?? "Existing assigned places"}{ex.expires ? ` · Until ${ex.expires}` : ""} · {ex.reason}</p></div><Badge tone={expired ? "neutral" : ex.decision === "deny" ? "red" : "green"}>{expired ? "Expired" : ex.decision === "deny" ? "Blocked" : "Allowed"}</Badge>{capability && !member.personas.includes("super_admin") && (!protectedMember || viewer === "super_admin") && <button className="min-h-11 px-2 text-sm font-semibold text-[#0a6b63]" onClick={() => actions.onEdit(capability, member)}>Edit</button>}</div>; })}</div>}
        </section>
        <section className={card}><div className="flex flex-wrap items-center justify-between gap-3 p-5"><div><h3 className="text-lg font-semibold">Inherited and effective access</h3><p className="text-sm text-[#58685f]">From every assigned persona, with member exceptions applied.</p></div><button className={secondary} onClick={() => setShowUnavailable((value) => !value)}>{showUnavailable ? "Hide unavailable" : "Show unavailable"}</button></div>
          {relevant.filter((item) => showUnavailable || effective(state, member, item).allowed).map((item) => { const result = effective(state, member, item); return <CapabilityRow key={item.action} capability={item} status={!item.implemented ? "Coming later" : result.allowed ? "Active" : result.source.startsWith("Blocked") ? "Restricted" : "No grant"} source={result.source} onDetails={() => actions.onDetails(item, member)} onEdit={item.implemented && !member.personas.includes("super_admin") && (!protectedMember || viewer === "super_admin") ? () => actions.onEdit(item, member) : undefined} />; })}
        </section>
      </>}
    </div>;
  }
  return <div className="space-y-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-2xl font-semibold">People</h2><p className="text-sm text-[#58685f]">Find a member, inspect their access and review exceptions.</p></div><button className={primary} onClick={onAddMember}>+ Add member</button></div>
    <div className={`${card} grid gap-3 p-4 md:grid-cols-[1fr_13rem_auto]`}><label className="text-sm font-medium">Search people<input className={`${field} mt-1`} type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Name or email" /></label><label className="text-sm font-medium">Persona<select className={`${field} mt-1`} value={filterPersona} onChange={(event) => setFilterPersona(event.target.value as Persona | "all")}><option value="all">All personas</option>{PERSONAS.filter((persona) => persona.id !== "super_admin").map((persona) => <option value={persona.id} key={persona.id}>{persona.label}</option>)}</select></label><label className="flex items-end gap-2 pb-3 text-sm"><input type="checkbox" checked={exceptionsOnly} onChange={(event) => setExceptionsOnly(event.target.checked)} />Has exceptions</label></div>
    <p className="text-sm text-[#58685f]">{visible.length} of {state.members.filter((item) => !item.personas.includes("super_admin")).length} demo members</p>
    {visible.length === 0 ? <Empty>No members match these filters.</Empty> : <div className={`${card} divide-y divide-[#e9efea]`}>{visible.map((item) => <div key={item.id} className="flex flex-wrap items-center gap-3 p-4 sm:px-5"><div className="grid size-11 shrink-0 place-items-center rounded-full bg-[#ddefec] font-semibold text-[#0a6b63]">{item.name.split(" ").map((part) => part[0]).slice(0, 2).join("")}</div><div className="min-w-48 flex-1"><p className="font-semibold">{item.name}</p><p className="text-sm text-[#58685f]">{item.email}</p></div><div className="min-w-40 flex-1 text-sm"><p>{item.personas.map(labelFor).join(" + ")}</p><p className="text-[#58685f]">{item.places.map((place) => place === "GLOBAL" ? "All depots" : place).join(", ") || "No place assigned"}{item.vehicleType ? ` · ${item.vehicleType === "van" ? "Van" : "Truck"}` : ""}</p></div>{state.exceptions.some((ex) => ex.memberId === item.id) && <Badge tone="amber">Exception</Badge>}<button className={secondary} onClick={() => { setSelected(item.id); setMemberTab("access"); }}>View access</button></div>)}</div>}
  </div>;
}

function Summary({ value, label }: { value: number; label: string }) { return <div className={`${card} p-5`}><p className="text-3xl font-semibold text-[#0a6b63]">{value}</p><p className="mt-1 text-sm text-[#58685f]">{label}</p></div>; }

export function PersonasScreen({ state, selected, setSelected, actions, viewer, onMembers, onAddMember }: { state: DemoState; selected: Persona | null; setSelected: (value: Persona | null) => void; actions: Actions; viewer: "admin" | "super_admin"; onMembers: (persona: Persona) => void; onAddMember: (persona: Exclude<Persona, "super_admin">) => void }) {
  const [module, setModule] = useState<"all" | string>("all");
  const [showLater, setShowLater] = useState(false);
  if (!selected) return <div className="space-y-7"><div><h2 className="text-2xl font-semibold tracking-[-.025em]">Personas</h2><p className="text-sm text-[#58685f]">Shared defaults for each role. Counts describe available action permissions, before place scope.</p></div>
    <section><h3 className="mb-3 text-lg font-semibold">Operational personas</h3><div className="grid gap-4 md:grid-cols-2 2xl:grid-cols-4">{PERSONAS.slice(0, 4).map((persona) => <PersonaCard key={persona.id} persona={persona.id} state={state} onOpen={() => { setSelected(persona.id); setModule("all"); }} onMembers={() => onMembers(persona.id)} />)}</div></section>
    <section><h3 className="mb-3 text-lg font-semibold">Administration</h3><div className="grid gap-4 md:grid-cols-2"><PersonaCard persona="admin" state={state} onOpen={() => { setSelected("admin"); setModule("all"); }} onMembers={() => onMembers("admin")} /></div></section>
  </div>;
  const info = PERSONAS.find((item) => item.id === selected)!;
  const relevant = CAPABILITIES.filter((item) => item.relevant.includes(selected) || state.personaSettings[`${selected}:${item.action}`]);
  const modules = [...new Set(relevant.map((item) => item.module))];
  const counts = personaCounts(state, selected);
  const members = state.members.filter((item) => item.personas.includes(selected));
  const permitted = (viewer === "super_admin" || selected !== "admin" && selected !== "super_admin") && selected !== "super_admin";
  const shown = relevant.filter((item) => (module === "all" || item.module === module) && (showLater || item.implemented));
  return <div className="space-y-5"><button className="min-h-11 text-sm font-semibold text-[#0a6b63]" onClick={() => setSelected(null)}>← Back to personas</button>
    <div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm text-[#58685f]">Personas / {info.label}</p><h2 className="mt-1 text-3xl font-semibold">{info.label} capabilities</h2><p className="text-[#58685f]">{info.description}</p></div><div className="flex flex-wrap gap-2">{selected !== "admin" && selected !== "super_admin" && <button className={primary} onClick={() => onAddMember(selected)}>+ Add member</button>}<button className={secondary} onClick={() => onMembers(selected)}>View {members.length} members</button></div></div>
    <div className="rounded-2xl border border-[#cbe5db] bg-[#eff9f3] p-4 text-sm">Changes to this persona affect all {members.length} assigned members within their existing place scope. Member exceptions may change the effective result.</div>
    <div className="flex flex-wrap gap-2"><Badge tone="green">{counts.active} active</Badge><Badge tone="blue">{counts.optional} optional</Badge><Badge tone="red">{counts.restricted} restricted</Badge><Badge tone="amber">{counts.later} coming later</Badge></div>
    <div className="grid gap-5 lg:grid-cols-[15rem_1fr]"><aside className={`${card} h-fit p-2`}><p className="px-3 py-2 text-xs font-bold uppercase tracking-wider text-[#66756b]">Modules</p>{["all", ...modules].map((name) => { const count = name === "all" ? relevant.filter((item) => item.implemented).length : relevant.filter((item) => item.module === name && item.implemented).length; return <button key={name} className={`flex min-h-11 w-full items-center justify-between rounded-xl px-3 text-left text-sm font-medium ${module === name ? "bg-[#ddefec] text-[#0a6b63]" : "hover:bg-[#f4f8f5]"}`} onClick={() => setModule(name)}><span>{name === "all" ? "All available" : name}</span><span className="text-xs">{count}</span></button>; })}</aside>
      <section className={card}><div className="flex flex-wrap items-center justify-between gap-3 border-b border-[#e9efea] p-5"><div><h3 className="text-lg font-semibold">{module === "all" ? "Available capabilities" : module}</h3><p className="text-sm text-[#58685f]">{shown.length} capabilities in this view</p></div><label className="flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" checked={showLater} onChange={(event) => setShowLater(event.target.checked)} /> Show coming later</label></div>
        {shown.length ? shown.map((item) => { const choice = personaChoice(state, selected, item.action); const active = personaAllows(state, selected, item.action); const status = !item.implemented ? "Coming later" : choice === "deny" ? "Restricted" : active ? "Active" : item.optionalFor?.includes(selected) ? "Optional" : "Restricted"; return <CapabilityRow key={item.action} capability={item} status={status} source={choice === "inherit" ? active ? "From published persona policy" : item.description : choice === "omit" ? "Not granted by this persona" : choice === "deny" ? "Explicitly blocked for this persona" : "Allowed for this persona"} onDetails={() => actions.onDetails(item, undefined, selected)} onEdit={item.implemented && permitted && (active || item.optionalFor?.includes(selected) || choice !== "inherit") ? () => actions.onEdit(item, undefined, selected) : undefined} />; }) : <div className="p-5"><Empty>No capabilities in this module and filter.</Empty></div>}
      </section></div>
  </div>;
}

function PersonaCard({ persona, state, protectedRole, onOpen, onMembers }: { persona: Persona; state: DemoState; protectedRole?: boolean; onOpen: () => void; onMembers: () => void }) {
  const info = PERSONAS.find((item) => item.id === persona)!; const counts = personaCounts(state, persona); const members = state.members.filter((item) => item.personas.includes(persona));
  return <article className={`${card} flex flex-col p-5 sm:p-6`}><div className="flex items-start justify-between gap-2"><div className="grid size-12 place-items-center rounded-2xl bg-[#d8f5ee] text-xl font-semibold text-[#006b57]">{persona === "driver" ? "↗" : persona === "loader" ? "▤" : persona === "store_manager" ? "▣" : persona === "dispatcher" ? "◎" : "◇"}</div>{protectedRole && <Badge tone="amber">Protected</Badge>}</div><h4 className="mt-5 text-xl font-semibold tracking-[-.02em]">{info.label}</h4><p className="mt-1 min-h-12 text-sm leading-6 text-[#58685f]">{info.description}</p><button className="mt-3 self-start text-sm font-semibold text-[#006b57] hover:underline" onClick={onMembers}>{members.length} assigned members →</button><div className="mt-5 grid grid-cols-3 gap-2 rounded-2xl bg-[#eef8f5] p-3 text-center"><div><strong className="block text-xl text-[#064f3f]">{counts.active}</strong><span className="text-xs text-[#52675d]">Active</span></div><div><strong className="block text-xl text-[#064f3f]">{counts.optional}</strong><span className="text-xs text-[#52675d]">Optional</span></div><div><strong className="block text-xl text-[#064f3f]">{counts.restricted}</strong><span className="text-xs text-[#52675d]">Restricted</span></div></div><p className="mt-3 text-xs text-[#62766a]">{counts.later} coming later</p><button className={`${secondary} mt-5 w-full`} onClick={onOpen}>{protectedRole ? "View governance" : "Manage capabilities"}</button></article>;
}

export function CatalogueScreen({ state, actions }: { state: DemoState; actions: Actions }) {
  const [query, setQuery] = useState(""); const [module, setModule] = useState("all"); const [availability, setAvailability] = useState("all");
  const modules = useMemo(() => [...new Set(CAPABILITIES.map((item) => item.module))], []);
  const rows = CAPABILITIES.filter((item) => (module === "all" || item.module === module) && (availability === "all" || item.implemented === (availability === "available")) && `${item.label} ${item.description} ${item.action}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="space-y-5"><div><h2 className="text-2xl font-semibold">Permission catalogue</h2><p className="text-sm text-[#58685f]">Search the capabilities represented in this demo. Technical action names are in details.</p></div><div className={`${card} grid gap-3 p-4 md:grid-cols-[1fr_12rem_12rem]`}><label className="text-sm font-medium">Search<input className={`${field} mt-1`} type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Capability or action" /></label><label className="text-sm font-medium">Module<select className={`${field} mt-1`} value={module} onChange={(event) => setModule(event.target.value)}><option value="all">All modules</option>{modules.map((name) => <option key={name}>{name}</option>)}</select></label><label className="text-sm font-medium">Availability<select className={`${field} mt-1`} value={availability} onChange={(event) => setAvailability(event.target.value)}><option value="all">All</option><option value="available">Available</option><option value="later">Coming later</option></select></label></div><p className="text-sm text-[#58685f]">{rows.length} capabilities</p>{rows.length ? <div className={card}>{rows.map((item) => <CapabilityRow key={item.action} capability={item} status={!item.implemented ? "Coming later" : "Available"} source={`${item.module} · ${item.relevant.map(labelFor).join(", ")}`} onDetails={() => actions.onDetails(item)} detailsLabel="Details" />)}</div> : <Empty>No capabilities match these filters.</Empty>}</div>;
}

export function HistoryScreen({ state }: { state: DemoState }) {
  const [query, setQuery] = useState("");
  const [selectedId, setSelectedId] = useState<number | null>(null);
  const selected = state.history.find((item) => item.id === selectedId);
  const title = (action: string) => CAPABILITIES.find((capability) => capability.action === action)?.label ?? action;
  const rows = state.history.filter((item) => `${item.target} ${item.action} ${title(item.action)} ${item.actor} ${item.reason}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => b.id - a.id);
  return <div className="space-y-5"><div><h2 className="text-2xl font-semibold">Change history</h2><p className="text-sm text-[#58685f]">Demo changes are recorded here with a reason and before/after choice.</p></div><label className="block max-w-md text-sm font-medium">Search changes<input className={`${field} mt-1`} value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Person, action or reason" /></label>{rows.length ? <div className={`${card} divide-y divide-[#e9efea]`}>{rows.map((item) => <article key={item.id} className="grid gap-2 p-5 sm:grid-cols-[11rem_1fr]"><time className="text-sm text-[#58685f]">{new Date(item.at).toLocaleString("en-LK", { dateStyle: "medium", timeStyle: "short", timeZone: "Asia/Colombo" })}</time><div><p className="font-semibold">{item.target} · {title(item.action)}</p><p className="mt-1 text-sm">{item.before} → {item.after}</p><p className="mt-1 text-sm text-[#58685f]">By {item.actor} · {item.reason}{item.place ? ` · ${item.place}` : ""}{item.expires ? ` · until ${item.expires}` : ""}</p><button className="mt-2 min-h-11 text-sm font-semibold text-[#0a6b63]" onClick={() => setSelectedId(item.id)}>View change</button></div></article>)}</div> : <Empty>No changes match this search.</Empty>}{selected && <Modal title="Change details" onClose={() => setSelectedId(null)}><dl className="grid gap-3 text-sm"><div><dt className="font-semibold">Target</dt><dd>{selected.target}</dd></div><div><dt className="font-semibold">Capability</dt><dd>{title(selected.action)}</dd></div><div><dt className="font-semibold">Change</dt><dd>{selected.before} → {selected.after}</dd></div><div><dt className="font-semibold">Actor and time</dt><dd>{selected.actor} · {new Date(selected.at).toLocaleString("en-LK", { dateStyle: "medium", timeStyle: "short", timeZone: "Asia/Colombo" })}</dd></div><div><dt className="font-semibold">Scope</dt><dd>{selected.place ?? "Assigned places"}</dd></div><div><dt className="font-semibold">Until</dt><dd>{selected.expires ?? "Until changed"}</dd></div><div><dt className="font-semibold">Reason</dt><dd>{selected.reason}</dd></div></dl><button className={`${secondary} mt-5`} onClick={() => setSelectedId(null)}>Close</button></Modal>}</div>;
}
