package com.waypoint.dispatch.referencedata.domain;

import java.math.BigDecimal;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.time.temporal.WeekFields;
import java.util.List;

/**
 * What happens past the end of the supplied calendar.
 *
 * <p>R-CAL-03. Planning silently stops working when the calendar runs out, so
 * days are generated by policy rather than left missing. Supplied dates are
 * authoritative and are never recomputed, and every generated day is marked so a
 * dispatcher can tell a real holiday from an assumed one.
 */
public final class OperatingCalendarPolicy {
  private OperatingCalendarPolicy() {}

  /** R-PLN-17: Waypoint operates Monday to Saturday. */
  public static boolean operatesOn(LocalDate date) {
    return date.getDayOfWeek() != DayOfWeek.SUNDAY;
  }

  public static CalendarDay generate(LocalDate date) {
    WeekFields iso = WeekFields.ISO;
    boolean weekend =
        date.getDayOfWeek() == DayOfWeek.SATURDAY || date.getDayOfWeek() == DayOfWeek.SUNDAY;
    return new CalendarDay(
        date,
        date.getDayOfWeek().getValue() - 1,
        weekend,
        date.get(iso.weekBasedYear()),
        date.get(iso.weekOfWeekBasedYear()),
        false,
        null,
        BigDecimal.ZERO,
        false,
        false,
        operatesOn(date),
        true);
  }

  /** Fills the gap between the last supplied day and the horizon, exclusive of the former. */
  public static List<CalendarDay> extendFrom(LocalDate lastSupplied, LocalDate horizon) {
    return lastSupplied
        .plusDays(1)
        .datesUntil(horizon.plusDays(1))
        .map(OperatingCalendarPolicy::generate)
        .toList();
  }
}
