import Icon from "./Icon";
import { personas, permissions, type ConsoleState, type AdminRole } from "./permissions.ts";
export default function Overview({ state, role, onNavigate }: { state: ConsoleState; role: AdminRole; onNavigate: (view: string) => void }) {
  const team = state.people.filter(p => p.role !== "admin");
  const cards = [
    { title: "Operational team", value: team.length, text: "Across four field roles", icon: "users", view: "people" },
    { title: "Active accounts", value: state.people.filter(p => p.status === "Active").length, text: `${state.people.filter(p => p.status === "Suspended").length} suspended account(s)`, icon: "check", view: "people" },
    { title: "Persona permissions", value: permissions.length, text: "Configurable by role or person", icon: "shield", view: "permissions" },
    { title: role === "super_admin" ? "Administrators" : "Depots", value: role === "super_admin" ? state.people.filter(p => p.role === "admin").length : 2, text: role === "super_admin" ? "Managed only by super admin" : "Peliyagoda and Kandy", icon: "pin", view: role === "super_admin" ? "admins" : "scopes" },
  ];
  return <>
    <section className="ac-hero"><div><span className="ac-eyebrow">THE RIGHT ACCESS. THE RIGHT PEOPLE.</span><h2>A connected team.<br/>A smoother delivery day.</h2><p>Give every person the tools they need, with clear boundaries for where they work.</p><button className="ac-button dark" onClick={() => onNavigate("permissions")}>Review role permissions<Icon name="arrow" size={17}/></button></div><div className="ac-hero-art" aria-hidden="true"><div className="ac-orbit one"/><div className="ac-orbit two"/><div className="ac-art-center"><Icon name="shield" size={42}/></div>{personas.map(p => <span key={p.id} className={`ac-art-node ${p.id}`}><Icon name={p.icon} size={25}/></span>)}</div></section>
    <div className="ac-stats">{cards.map(c => <button key={c.title} className="ac-stat" onClick={() => onNavigate(c.view)}><span>{c.title}<Icon name={c.icon} size={18}/></span><strong>{c.value.toString().padStart(2, "0")}</strong><small>{c.text}</small></button>)}</div>
    <div className="ac-section-title"><div><h2>Four roles. One connected workflow.</h2><p>Permission defaults grounded in the challenge booklet.</p></div><button className="ac-text-button" onClick={() => onNavigate("permissions")}>Manage permissions <Icon name="arrow" size={16}/></button></div>
    <div className="ac-role-cards">{personas.map(p => <article className="ac-role-card" key={p.id}><span className={`ac-role-icon ${p.id}`}><Icon name={p.icon} size={23}/></span><small className="ac-eyebrow">{p.short}</small><h3>{p.name}</h3><p>{p.description}</p><div><span>{team.filter(u => u.role === p.id).length} people</span><span>{state.templates[p.id].length} permissions</span></div><footer><Icon name="pin" size={14}/>{p.scope}</footer></article>)}</div>
    <div className="ac-overview-bottom"><section className="ac-panel"><div className="ac-panel-heading"><div><h2>Recent activity</h2><p>A clear record of access changes.</p></div><button className="ac-text-button" onClick={() => onNavigate("activity")}>View all <Icon name="arrow" size={16}/></button></div>{state.activity.slice(0, 3).map(a => <div className="ac-activity-row" key={a.id}><span className="ac-activity-dot"><Icon name="shield" size={16}/></span><div><strong>{a.action}</strong><p>{a.target} · {a.actor}</p><small>{new Date(a.at).toLocaleString("en-GB", { timeZone: "Asia/Colombo" })} · Colombo</small></div></div>)}</section><section className="ac-access-note"><Icon name="lock" size={25}/><h3>Two levels of administration</h3><p><strong>Super admin</strong> has full access and exclusively creates and manages admins.</p><p><strong>Admin</strong> assigns the four operational roles, controls their scope and toggles permissions.</p><span>Field roles cannot administer access.</span></section></div>
  </>;
}
