"use client";
import { useState } from "react";
import Icon from "./Icon";
import { effectivePermissions, personas, roleName, type Person, type Templates } from "./permissions.ts";
export function Avatar({ name }: { name: string }) { return <span className="ac-avatar">{name.split(" ").slice(0, 2).map(n => n[0]).join("")}</span>; }
export default function PeoplePanel({ people, templates, admins = false, scopes = false, onEdit }: { people: Person[]; templates: Templates; admins?: boolean; scopes?: boolean; onEdit: (p: Person) => void }) {
  const [search, setSearch] = useState("");
  const [role, setRole] = useState("all");
  const [status, setStatus] = useState("all");
  const filtered = people.filter(p => (admins ? p.role === "admin" : p.role !== "admin") && (role === "all" || p.role === role) && (status === "all" || p.status === status) && `${p.name} ${p.email} ${p.scope.join(" ")}`.toLowerCase().includes(search.toLowerCase()));
  return <section className="ac-panel"><div className="ac-table-toolbar"><label className="ac-search"><Icon name="search" size={18}/><input aria-label="Search people" placeholder="Search name, email or assignment…" value={search} onChange={e => setSearch(e.target.value)}/></label><div className="ac-filters">{!admins && <select aria-label="Filter by role" value={role} onChange={e => setRole(e.target.value)}><option value="all">All roles</option>{personas.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select>}<select aria-label="Filter by status" value={status} onChange={e => setStatus(e.target.value)}><option value="all">All statuses</option><option>Active</option><option>Suspended</option></select></div></div>
    <div className="ac-table-scroll"><table><thead><tr><th>Team member</th><th>Role</th><th>{scopes ? "Assignment & validity" : "Access scope"}</th><th>Status</th><th>{scopes ? "Access rules" : "Permissions"}</th><th><span className="ac-sr-only">Manage account</span></th></tr></thead><tbody>{filtered.map(p => <tr key={p.id}><td><div className="ac-person-cell"><Avatar name={p.name}/><div><strong>{p.name}</strong><small>{p.email}</small></div></div></td><td><span className={`ac-role-label ${p.role}`}>{roleName(p.role)}</span></td><td><div className="ac-scope-cell">{p.role === "admin" ? "Operational team" : p.scope.join(", ")}{p.role === "driver" && <small>{p.from} → {p.until}</small>}</div></td><td><span className={`ac-badge ${p.status === "Active" ? "green" : "amber"}`}><i/>{p.status}</span></td><td>{scopes ? <span className="ac-muted">{p.role === "driver" ? "Vehicle + date" : "Assigned scope only"}</span> : p.role === "admin" ? <span className="ac-muted">Team administration</span> : <><strong className="ac-count">{effectivePermissions(p, templates).length}</strong><span className="ac-muted"> enabled</span>{Object.keys(p.overrides).length > 0 && <small className="ac-custom">Custom overrides</small>}</>}</td><td><button className="ac-row-action" aria-label={`Manage ${p.name}`} onClick={() => onEdit(p)}><Icon name="arrow" size={18}/></button></td></tr>)}</tbody></table></div>
    {filtered.length === 0 && <div className="ac-empty"><Icon name="users" size={32}/><h3>No people found</h3><p>Try another name or clear your filters.</p><button className="ac-button" onClick={() => { setSearch(""); setRole("all"); setStatus("all"); }}>Clear filters</button></div>}
    <div className="ac-table-footer">{filtered.length} {filtered.length === 1 ? "account" : "accounts"}<span>Access is limited to each person’s assignment.</span></div>
  </section>;
}
