package com.waypoint.dispatch.referencedata.web;

import com.waypoint.dispatch.platform.web.RequestAuthorizer;
import com.waypoint.dispatch.referencedata.contract.ReferenceQuery;
import com.waypoint.dispatch.referencedata.contract.ReferenceViews.CalendarDayView;
import com.waypoint.dispatch.referencedata.contract.ReferenceViews.OutletView;
import com.waypoint.dispatch.referencedata.contract.ReferenceViews.VehicleView;
import com.waypoint.dispatch.shared.error.DomainException;
import com.waypoint.dispatch.shared.error.ErrorCode;
import jakarta.servlet.http.HttpServletRequest;
import java.time.LocalDate;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

/**
 * Reading outlets, fleet and the calendar.
 *
 * <p>Every endpoint takes an optional {@code version}. Omitting it means the
 * version currently in use; naming one replays exactly what that version held,
 * which is what makes a past decision reproducible rather than merely recorded.
 * The loaded version is exposed so a stale instance is visible on screen instead
 * of quietly answering from last week's data.
 *
 * <p>Reads only. Importing a version and overriding a calendar day are both
 * commands, because both are decisions that need a receipt and an audit row.
 *
 * <p>Authorization goes through the {@code RequestAuthorizer} port rather than the
 * identity module directly: a module's web layer may not import another module.
 */
@RestController
@RequestMapping("/api/reference")
public class ReferenceController {
  private static final String READ = "reference:Read";

  private final ReferenceQuery reference;
  private final RequestAuthorizer authorizer;

  public ReferenceController(ReferenceQuery reference, RequestAuthorizer authorizer) {
    this.reference = reference;
    this.authorizer = authorizer;
  }

  /** What every other answer on this controller was computed from. */
  @GetMapping("/version")
  public Map<String, String> version(HttpServletRequest request) {
    authorizer.require(request, READ, "wpt:ref:version:*");
    return Map.of("versionId", reference.currentVersionId().map(UUID::toString).orElse(""));
  }

  @GetMapping("/outlets")
  public List<OutletView> outletsOfDepot(
      @RequestParam String depot,
      @RequestParam(required = false) String version,
      HttpServletRequest request) {
    authorizer.require(request, READ, "wpt:ref:depot:" + depot);
    return reference.outletsOfDepot(depot, uuid(version));
  }

  @GetMapping("/outlets/{outletId}")
  public OutletView outlet(
      @PathVariable String outletId,
      @RequestParam(required = false) String version,
      HttpServletRequest request) {
    authorizer.require(request, READ, "wpt:ref:outlet:" + outletId);
    return reference
        .outlet(outletId, uuid(version))
        .orElseThrow(() -> new DomainException(ErrorCode.NOT_FOUND, "No outlet " + outletId));
  }

  /**
   * The fleet a depot can actually use on a date: vehicles minus workshop and
   * unavailable. Answering with the whole fleet and letting the caller filter is
   * how a broken truck gets planned.
   */
  @GetMapping("/vehicles")
  public List<VehicleView> availableVehicles(
      @RequestParam String depot,
      @RequestParam String date,
      @RequestParam(required = false) String version,
      HttpServletRequest request) {
    authorizer.require(request, READ, "wpt:ref:depot:" + depot);
    return reference.availableVehicles(depot, date(date), uuid(version));
  }

  @GetMapping("/vehicles/{vehicleId}")
  public VehicleView vehicle(
      @PathVariable String vehicleId,
      @RequestParam(required = false) String version,
      HttpServletRequest request) {
    authorizer.require(request, READ, "wpt:ref:vehicle:" + vehicleId);
    return reference
        .vehicle(vehicleId, uuid(version))
        .orElseThrow(() -> new DomainException(ErrorCode.NOT_FOUND, "No vehicle " + vehicleId));
  }

  /**
   * Answers even for a date past the end of the supplied calendar, where the day
   * is generated by policy and says so. R-CAL-03: a dispatcher has to be able to
   * tell a real holiday from an assumed one, so {@code generated} is in the body.
   */
  @GetMapping("/calendar/{date}")
  public Map<String, Object> day(@PathVariable String date, HttpServletRequest request) {
    authorizer.require(request, READ, "wpt:ref:calendar:" + date);
    LocalDate on = date(date);
    CalendarDayView view = reference.day(on).orElse(null);
    return Map.of(
        "date", on.toString(),
        "operating", reference.isOperating(on),
        "nextOperatingDay", reference.nextOperatingDay(on).toString(),
        "known", view != null,
        "day", view == null ? Map.of() : view);
  }

  private static UUID uuid(String value) {
    if (value == null || value.isBlank()) {
      return null;
    }
    try {
      return UUID.fromString(value);
    } catch (IllegalArgumentException e) {
      throw new DomainException(ErrorCode.VALIDATION_FAILED, "version is not a uuid: " + value);
    }
  }

  private static LocalDate date(String value) {
    try {
      return LocalDate.parse(value);
    } catch (RuntimeException e) {
      throw new DomainException(
          ErrorCode.VALIDATION_FAILED, "Expected a date as yyyy-mm-dd, not " + value);
    }
  }
}
